import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "../components/theme-provider";
import { ThemeButton } from "../components/ThemeButton";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from '@clerk/themes'
import { TooltipProvider } from "@/components/ui/tooltip"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "One Stop Hub",
  description: "Generated by create next app",
};

import { StarsBackground } from "@/components/ui/stars-background";
import { ShootingStars } from "@/components/ui/shooting-stars";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    >
      <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        suppressHydrationWarning
      >
        <body className="min-h-full flex flex-col relative">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            {/* Global Background Effects (Hidden on mobile for performance/battery) */}
            <div className="fixed inset-0 pointer-events-none z-0 hidden md:block">
              <StarsBackground starDensity={0.00015} />
              <ShootingStars />
            </div>

            {/* Main Application Content */}
            <div className="relative z-10 flex flex-col flex-1 min-h-full w-full">
              <TooltipProvider>{children}</TooltipProvider>
            </div>
            <div className="fixed bottom-6 right-6 z-50">
              <ThemeButton />
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
